version: '3.5'
services:
  web: 
    build:
      context: .
    ports: 
      - "3001:80"
    ipc: host

  test:
    build:
      context: .
      target: build-stage
    environment:
      - NODE_ENV=development
    command: npm run test
