version: '3.5'
services:
  web: 
    build:
      context: .
    ports: 
      - "3000:80"
    ipc: host

  test:
    build:
      context: .
      target: builder
    environment:
    - NODE_ENV=development
    command: npm run test
